### ISSUE TITLE
Could not make argcomplete work with zsh

### ISSUE THREAD

**Issue by Gim6626** [kislyuk/argcomplete#330] opened 2020-11-12 08:16 UTC
Tried to follow zsh autocomplete configuration guide from https://pypi.org/project/argcomplete/ (section "Zsh Support") but haven't succeeded.

If I add to `.zshrc` this (as in guide):
```
autoload -U bashcompinit
bashcompinit
eval "$(register-python-argcomplete /Users/d.vinokurov/work/lptl/lptl.py)"
```

Then I got error on zsh start:
```
complete:13: command not found: compdef
```

Googled it and found solution, now my `.zshrc` is such:
```
autoload -Uz compinit
compinit
autoload -U bashcompinit
bashcompinit
eval "$(register-python-argcomplete /Users/d.vinokurov/work/lptl/lptl.py)"
```

Now zsh prints:
```
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]?
```

`compaudit` shows:
```
There are insecure directories:
/usr/local/share/zsh/site-functions
/usr/local/share/zsh
```

So I think it is not related to argcomplete. Pressed "y" but autocomplete still don't work.

Googled more and found that I need to source bash autocomplete script. So changed my autocomplete section in `.zshrc`:
```
autoload -Uz compinit
compinit
autoload -U bashcompinit
bashcompinit
source /Users/d.vinokurov/.bash_completion.d/python-argcomplete
eval "$(register-python-argcomplete /Users/d.vinokurov/work/lptl/lptl.py)"
```

But it does not work too.

Please help me.

**Comment by evanunderscore** [comment] 2020-11-27 04:24
These are the instructions I have previously used to get this working with zsh: https://github.com/kislyuk/argcomplete/issues/10#issuecomment-19369876

It's possible that this is no longer working in newer versions of zsh. Which version are you running?

Have you confirmed that the script you're trying to complete works in another shell, e.g. Bash?

**Comment by shahzebsiddiqui** [comment] 2021-02-03 13:57
I ran into same issue i had to run 

```
autoload -Uz compinit
compinit
```

I am using following version on a Mac

```
(buildtest) siddiq90@DOE-7086392 buildtest % zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

I have a setup.sh script which i use to install buildtest and depending on the shell i activate the auto complete feature. It's not clear if `autoload -Uz compinit` and `compinit` commands are required or it depends on user shell setup


```

buildtest_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"
pip=pip3

if ! [ -x "$(command -v $pip)" ]; then 
  echo "cannot find program $pip, please install $pip"
  exit 1
fi

echo "Installing buildtest dependencies"
$pip install -r ${buildtest_root}/requirements.txt &> /dev/null

bin=${buildtest_root}/bin
export PATH=${bin}:$PATH
# add PYTHONPATH for buildtest to persist in shell environment
export PYTHONPATH=${buildtest_root}:$PYTHONPATH

# autocomplete buildtest with argcomplete see: https://kislyuk.github.io/argcomplete/#
if [[ "$SHELL" == "/bin/bash" ]]; then
  eval "$(register-python-argcomplete buildtest)"
elif [[ "$SHELL" == "/bin/zsh" ]]; then
  autoload -Uz compinit
  compinit
  autoload -U bashcompinit
  bashcompinit
  eval "$(register-python-argcomplete buildtest)"
fi

buildtest_path=$(which buildtest)
echo "buildtest command: ${buildtest_path}"
```

Once i ran the script it worked but i was prompted with `compinit` which i pressed **y**

```
(buildtest) siddiq90@DOE-7086392 buildtest % source setup.sh 
Installing buildtest dependencies
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? y
buildtest command: /Users/siddiq90/Documents/buildtest/bin/buildtest
```


The tab complete was working after this

```
(buildtest) siddiq90@DOE-7086392 buildtest % buildtest
--debug     --version   -d          build       config      inspect     schema      
--help      -V          -h          buildspec   docs        report      schemadocs 
```

**Comment by kislyuk** [comment] 2023-03-19 09:26
Thanks for your interest in argcomplete. After an extensive attempt to reproduce your issue, I'm unable to do so. Zsh support works for me as described in the readme, on both Mac OS 12 and Ubuntu 22.04.

If you still need help, please describe your exact environment and steps to reproduce from a new install.

To help maintainers focus, am going to close this issue for now. Please feel free to comment if you have further information.

**Closed by kislyuk** 2023-03-19 09:26 UTC
