### ISSUE TITLE
Does argcomplete special case = (equals signs)?

### ISSUE THREAD

**Issue by asmeurer** [kislyuk/argcomplete#94] opened 2015-02-16 20:12 UTC
Does argcomplete special case equals signs, or am I doing this wrong?

For conda, I want to complete `conda install packagename=version`, like `conda install python=3.3`. I am using

``` py

# To get tab completion from argcomplete
class Completer(object):
    @memoize
    def get_items(self):
        return self._get_items()

    def __contains__(self, item):
        # This generally isn't all possibilities, and even if it is, we want
        # to give better error messages than argparse
        return True

    def __iter__(self):
        return iter(self.get_items())

class Packages(Completer):
    def __init__(self, prefix, parsed_args, **kwargs):
        self.prefix = prefix
        self.parsed_args = parsed_args

        self.has_eq = '=' in prefix

    def _get_items(self):
        # TODO: Include .tar.bz2 files for local installs.
        from conda.api import get_index
        args = self.parsed_args
        index = get_index(channel_urls=args.channel or (), use_cache=True,
            prepend=not args.override_channels, unknown=args.unknown,
            offline=args.offline)
        if not self.has_eq:
            return [i.rsplit('-', 2)[0] for i in index]
        else:
            return [i.rsplit('-', 2)[0] + '=' + i.rsplit('-', 2)[1] for i in index]
```

Sorry that the code is a little complicated. I have a lot of completers. 

The idea is that if the package doesn't contain a `=`, we just return a list of packages (because the common case is to not include any `=` at the command line, like `conda install numpy`). If it does, I want to complete to `package=version`. But this is giving

```
$PYTHONPATH=. conda install numpy= # I press TAB here
numpy\=1.5.1     numpy\=1.6.2     numpy\=1.7.0     numpy\=1.7.0b2   numpy\=1.7.0rc1  numpy\=1.7.1     numpy\=1.8.0     numpy\=1.8.1     numpy\=1.8.2     numpy\=1.9.0     numpy\=1.9.1
$PYTHONPATH=. conda install numpy=numpy\=1.
```

(the PYTHONPATH is to make sure I am using the git master of argcomplete to test if this was already fixed)

How do I get the behavior I want?

**Comment by wapiflapi** [comment] 2015-02-17 08:50
I'm taking a look at this. Bellow is a simple script I used to reproduce the issue.

Use like this: `./test_script.py foo` to get completions for `'foo'`, which should produce `'foo=bar'` but gives `'foo\\=bar'` instead. 

```python
#!/usr/bin/env python3

import sys
import argparse
import argcomplete

line = " ".join(sys.argv)

parser = argparse.ArgumentParser()
parser.add_argument("pick", choices=["foo,bar", "spam=eggs"])

completer = argcomplete.CompletionFinder(
    parser, always_complete_options=True)

(cword_prequote, cword_prefix, cword_suffix,
 comp_words, first_colon_pos) = argcomplete.split_line(line)

completions = completer._get_completions(
    comp_words, cword_prefix, cword_prequote, first_colon_pos)

print("completions for: %r" % line)
print(completions)
```

**Comment by wapiflapi** [comment] 2015-02-17 09:05
Ok, so basically this seems to be a feature. I'm not sure when its helpful but it's being done on purpose. `quote_completions` escapes all characters that bash splits words on. It gets this from `environ['_ARGCOMPLETE_COMP_WORDBREAKS']` or `environ['COMP_WORDBREAKS']` if none of those are set it falls back to `" \t\"'@><=;|&(:."`.

Now, I'm not sure if that default set is sensible because I don't know the implications of, say, not escaping `'='`. Maybe @kislyuk has a better grip on this than me.

In the meantime you can either overwrite the `quote_completions` in a subclass of `CompleterFinder` or add on of the environment variables mentioned above.

Regarding code changes to argcomplete, it's probably worth having the default set as an attribute to make it easier to overwrite. Again I'dd like @kislyuk's input on this before doing a PR.

Hope this helps!

**Comment by kislyuk** [comment] 2015-02-17 16:09
I can't reproduce your issue. Yes, the equals signs are among characters that are escaped. Bash processes the escapes, and they should not show up on or interfere with completions on the command line. @asmeurer, can you provide an end-to-end repro script?

**Comment by kislyuk** [comment] 2015-02-17 16:18
Never mind. I had `COMP_WORDBREAKS` set to nothing. Unsetting it induces the default value that @wapiflapi pointed out.

I'll have to think a bit about this, the behavior for `=` seems similar to `:` and may have to be special-cased in the same way. In the meantime, starting your input with a quote will unbreak the completions.

**Comment by asmeurer** [comment] 2015-02-17 17:09
Apparently `\=` is treated as `=` in bash. The problem is that it duplicates the input (`numpy=<TAB>` becomes `numpy=numpy\=1.` instead of just `numpy=1.` or `numpy\=1.` Or am I using the `prefix` argument to the completer incorrectly?

**Comment by asmeurer** [comment] 2015-02-17 17:10
And obviously having it use just `=` instead of `\=` is preferable, as `\=`is going to confuse almost all of our users.

**Comment by wapiflapi** [comment] 2015-02-17 18:47
I didn't notice the duplication in your example earlier. I **can't** reproduce this with bash or repl-style using the code included bellow. I'm not sure I'm not making a mistake here so please let me know if this code does produce the bug on your setup. It might be worth checking you're up to date as well since #93 was merged after you posted this issue and might have had an effect on obscure readline related stuff (which this probably is).

```python
#!/usr/bin/env python3

import sys
import argparse
import argcomplete


def Completer(**kwargs):
    return ["foo=spam", "foo=eggs"]

parser = argparse.ArgumentParser()
parser.add_argument("pick").completer = Completer

argcomplete.autocomplete(parser)
# when testing autocompletion with bash the script will stop here.
# bellow is just for REPL testing.

line = " ".join(sys.argv)

completer = argcomplete.CompletionFinder(
    parser, always_complete_options=True)

(cword_prequote, cword_prefix, cword_suffix,
 comp_words, first_colon_pos) = argcomplete.split_line(line)

completions = completer._get_completions(
    comp_words, cword_prefix, cword_prequote, first_colon_pos)

print("repl completions for: %r" % line)
print(completions)
```

As for the fact `'='` will confuse users I agree, I see no reason for this character to be among the default word-break characters. So you're probably safe to just overwrite those.

**Comment by asmeurer** [comment] 2015-02-17 19:22
Yeah, seems to happen in master (assuming the `PYTHONPATH=.` is working correctly).

**Comment by kislyuk** [comment] 2015-03-02 14:38
@asmeurer, could you please paste a full repro of this together with the value of `COMP_WORDBREAKS` (or lack thereof) in the shell that you're using it from? I think I have a fix for you, but I want to be sure.

**Comment by asmeurer** [comment] 2015-03-02 17:07
```
$echo $COMP_WORDBREAKS
"'><=;|&(:
```

```py
#!/usr/bin/env python
import argparse

import argcomplete
# PYTHON_ARGCOMPLETE_OK

a = ['a', 'b', 'c']
b = ['1', '2', '3']
choices = ['%s=%s' % (i, j) for i in a for j in b]

p = argparse.ArgumentParser("test")
p.add_argument('testing', choices=choices)

argcomplete.autocomplete(p)

args = p.parse_args()
```

```
$./test.py a=<TAB>
a\=1  a\=2  a\=3
$./test.py a=a\=
```

**Comment by asmeurer** [comment] 2015-03-02 17:08
Oh and the shell is Bash 4.3.33(1)-release.

**Comment by kislyuk** [comment] 2015-03-03 03:47
Sorry, I can't reproduce your problem at all.

**Comment by asmeurer** [comment] 2015-03-04 01:13
If you push your fix to a branch I can test it.

**Comment by kislyuk** [comment] 2015-03-04 02:30
Pushed to https://github.com/kislyuk/argcomplete/tree/issue-94, but I'm not sure I like that fix because presumably it escapes characters whose escaping is otherwise necessary.

I wonder if what you're observing is the result of unsetting COMP_WORDBREAKS (which, as the docs say, results in permanent disabling of its functionality, and causes bash to revert to some sort of default behavior, though I'm not entirely clear on that).

**Comment by wapiflapi** [comment] 2015-03-04 03:05
Looking at that patch I noticed we have a bunch of ifs checking python 2 versus python 3. I haven't noticed this before and have never tried to reproduce using python 2. Maybe this could explain why we are observing different results?

**Comment by asmeurer** [comment] 2015-03-04 05:46
I use Python 3.

**Comment by tjprescott** [comment] 2016-08-10 18:27
> Ps: Also make sure your splitting and building of the return strings in your completer is working as >expected. Maybe try to return ["numpy=1", "numpy=2"] just to eliminate that possibility.

@wapiflapi @kislyuk In my use case I'm doing exactly the above and it gives me the \=. Has there been any progress on this issue?

**Comment by kislyuk** [comment] 2016-08-11 00:38
@tjprescott, does my fix in the branch (https://github.com/kislyuk/argcomplete/tree/issue-94) work for you?

**Comment by tjprescott** [comment] 2016-08-11 18:48
@kislyuk no, that didn't work. I even tried using empty string for punctuation_chars and just space for the default comp_wordbreaks and the = characters in my completions are all still escaped.

**Comment by kislyuk** [comment] 2016-08-12 00:19
@tjprescott, that's strange. When I hardcode comp_wordbreaks in the code to be empty, my raw (unquoted) completions don't get escaped. Are you sure the code you modify is what gets loaded?

The showstopper problem is that not escaping `=` breaks unquoted completions because bash splits words on `=` and mangles the resulting command line state (repeating the portion before the `=`). There might be a way around this by changing `COMP_WORDBREAKS` in the shell before calling the completion script, but from what I know, that leaks unacceptable side effects into the shell's global state.

I believe there is nothing I can do about this. If you can find a solution, please feel free to submit a patch.

**Comment by tjprescott** [comment] 2016-08-12 14:13
@kislyuk I am sure that the modified code is what is loaded. I added some letters to the set and it started escaping those, but for some reason I can't get it to unescape the equals sign.

We are using it to provide partial completion of a key=value pair--i.e. argcomplete is completing the key name. So it just means that the user has to manually type the =. Not a huge deal. :)

**Comment by evanunderscore** [comment] 2016-10-25 13:26
I'm guessing the deafult word breaks include `=` so that you could tab complete something as both `--foo <tab>` and `--foo=<tab>` or similar. The same is likely true for `:`, which is being worked around specifically [here](https://github.com/kislyuk/argcomplete/blob/308255ed67e32ce2d68d624d108aa2590c8b5d36/argcomplete/__init__.py#L511). The "mangling" is the same thing @asmeurer is talking about where bash views the completion as starting after the `=`, and so inserts the entire completion after that point, resulting in `numpy=numpy=1.`.

This should be fixable by doing the following:
1. **Not** treating `COMP_WORDBREAKS` as "special characters" (i.e. characters that need to be escaped) [here](https://github.com/kislyuk/argcomplete/blob/308255ed67e32ce2d68d624d108aa2590c8b5d36/argcomplete/__init__.py#L515)
2. Extending the `:` fix [here](https://github.com/kislyuk/argcomplete/blob/308255ed67e32ce2d68d624d108aa2590c8b5d36/argcomplete/__init__.py#L513) to any characters that are in `COMP_WORDBREAKS` but are not otherwise considered special to the shell (since they will be escaped regardless).

It's also worth considering this would be going above and beyond what bash's default tab completion is capable of. Creating files called `foo=bar` or `foo:bar` and trying to tab complete them exhibits these same problems.

An alternative might be to expose this concept to the completers somehow, but I'm not entirely sure what that would look like.

**Comment by evanunderscore** [comment] 2017-01-03 06:20
I have a branch with this implemented. Since it doesn't match bash's default behavior, should it be opt-in?

**Comment by asmeurer** [comment] 2017-01-03 08:48
My vote would be to just have it do the right thing. If bash/readline doesn't tab complete files with `=` in them correctly then that's a bug in bash as well IMHO.

**Comment by evanunderscore** [comment] 2017-01-03 12:10
"The right thing" is subjective. Completion is supposed to split on COMP_WORDBREAKS, so if you don't want to split on those characters, you have to escape them. However there's a case to be made that COMP_WORDBREAKS are relevant in a general shell context but are largely meaningless to argparse, so argcomplete should just work around them.

See also: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=674084

**Comment by kislyuk** [comment] 2017-01-03 15:42
@evanunderscore, which branch is your fix in? Is it #172?

**Comment by evanunderscore** [comment] 2017-01-03 22:52
There's no PR yet, but the branch is [here](https://github.com/evanunderscore/argcomplete/tree/wordbreaks). It's only the last commit that directly addresses this problem. The branch needs a little bit more work but it will work for Bash if you run it now.

**Comment by evanunderscore** [comment] 2017-01-14 05:54
@asmeurer, @tjprescott: Can you confirm #187 fixes your issue?

**Comment by asmeurer** [comment] 2017-01-16 22:58
Well I apparently cannot reproduce my own issue (this is a different computer and it was a while ago). I now get the `\=` behavior, with no duplication for my test script https://github.com/kislyuk/argcomplete/issues/94#issuecomment-76752708. But the good news is your branch #187 doesn't add the \ when completing, so in that respect it is better.

**Comment by evanunderscore** [comment] 2017-01-17 07:48
I'm still seeing the bugged behavior when I run from master, i.e. `a<tab>` yields `a\=` but `a=<tab>` yields `a=a\=`. The problem previously only occurred when the user had typed an unescaped equals sign, which is probably why some people were having trouble reproducing the bug.

**Comment by asmeurer** [comment] 2017-01-17 08:15
@evanunderscore oh you're right. I just checked again and I can confirm that the #187 branch fixes this completely.

**Comment by evanunderscore** [comment] 2017-01-17 09:27
Cool, thanks for verifying. I'll merge this in.

**Closed** 2017-01-17 09:31 UTC

**Comment by asmeurer** [comment] 2017-01-17 19:13
Awesome. Can you let me know when this gets into a release? I'd like to get that change I originally was trying to make into conda.

**Comment by evanunderscore** [comment] 2017-01-19 12:08
@kislyuk When do you think the next release will be?

**Comment by kislyuk** [comment] 2017-01-19 15:25
Released v1.8.0.

**Comment by kislyuk** [comment] 2017-01-19 16:22
@evanunderscore FYI: https://travis-ci.org/kislyuk/argcomplete/jobs/193414829

I can restart the test, but wanted to make you aware of this intermittent failure.

**Comment by evanunderscore** [comment] 2017-01-19 22:29
Thanks! I've seen that intermittent failure before - I think it's because the Travis OSX builders are under heavy load and respond really slowly. I'll try increasing the timeout and see if that helps.

**Comment by evanunderscore** [comment] 2017-01-22 01:34
@asmeurer There was a bug in 1.8.0. 1.8.1 has now been released.
